name: github_explorer
version: 1.0.0+1
publish_to: none
description: github_explorer | search for respository.
environment: 
  sdk: '>=2.19.6 <3.0.0'
dependencies: 
  provider: ^6.0.5
  go_router: ^6.0.1
  flutter_native_splash: ^2.2.16
  flutter_translate: ^4.0.3
  get_it: ^7.2.0
  desktop_window: ^0.4.0
  dio: ^4.0.6
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  device_info_plus: ^8.0.0
  android_id: ^0.1.3+1
  jwt_decode: ^0.3.1
  icon_font_generator: ^3.2.0
  flutter_device_type: ^0.4.0
  flutter_keyboard_visibility: ^5.4.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.5
  pull_to_refresh: ^2.0.0
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
dev_dependencies: 
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_lints: ^1.0.0
flutter: 
  fonts: 
    - family: Montserrat
      fonts: 
      - 
          asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          style: normal
          weight: 100
      - 
          asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          style: normal
          weight: 300
      - 
          asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          style: normal
          weight: 400
      - 
          asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          style: normal
          weight: 700
      - 
          asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          style: normal
          weight: 900
    - family: FASolid
      fonts:
        - asset: assets/fonts/fasolid.ttf
    - family: FARegular
      fonts:
        - asset: assets/fonts/faregular.ttf
  assets: 
    - assets/
    - assets/images/
    - assets/i18n/
    - assets/icon/
    - assets/icons/
    - assets/fonts/
    - .env
  uses-material-design: true
flutter_native_splash: 
  color: '#24292F'
  image: assets/images/splash.png
  android: true
  ios: true
  web: true
flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.jpg
  web: 
    image_path: assets/icon/icon.jpg
    generate: true
  windows: 
    image_path: assets/icon/icon.jpg
    generate: true
  ios: true
